### ISSUE TITLE
Thread safety with Puma

### ISSUE THREAD

**Issue by kushkella** [LTe/grape-rabl#37]
During Puma's phased restart, it often happens that the endpoint context is no longer available to the Rabl template which causes it throw errors. e.g. a helper defined in the Grape endpoint which is usually available to Rabl templates to use is no longer available because the context has been replaced/removed. 

Since Grape-Rabl uses the ```api.endpoint``` key set in the environment, it is possible that the env is replaced before the rendering is finished. I'm not sure if this is a problem that should be fixed in ```Grape``` or ```Grape::Rabl```. I'm only seeing this problem when running Grape with mult-threaded Puma server. It would be great if you can help me out. Thanks!

**Comment by dblock** [comment]
This might be related: https://github.com/nesquena/rabl/issues/471

**Comment by kushkella** [comment]
I don't think so. If this were to be related, I would see errors even without restarting puma. It seems that the way grape-rabl works using a Grape::Formatter middleware, Grape doesn't really keep the environment for the formatter middleware when a restart signal sent.

Maybe I'm completely off-track, but I'm confident that with concurrent requests and mult-threaded environment I don't see any errors unless I restart Puma.

**Comment by dblock** [comment]
I see. How does this problem manifest itself? Exception? Got a stack? Restart under load?

**Comment by kushkella** [comment]
Whenever there are concurrent requests and a phased restart is issued, the request whichever is in progress fails to render the Rabl template because it either isn't able to find a helper or the instance variable set in the endpoint etc. 

To be more precise since Rabl evaluates the template code in the context of the endpoint such that it has access to instance variables and helper methods of the context, it fails. I think this is because the helpers or instance variables or the entire context is gone for some reason.

I'm able to reproduce this with ab -n 10000 -c 2.

Thanks!

**Comment by kushkella** [comment]
The stack essentially says that helper method not found which is defined in the Grape endpoint.

**Comment by dblock** [comment]
So the endpoint is blown away before rendering code is finished. So something needs to hold onto the reference to the endpoint (I thought https://github.com/LTe/grape-rabl/blob/master/lib/grape-rabl/formatter.rb#L12 would be enough, but maybe not).  

Maybe reloading should first drain connections, that'd be prudent, no?

**Comment by kushkella** [comment]
It should be the case. But I'm not sure how we can do that. Probably the way I'm running grape is causing these issues. I've mounted grape inside Rails and Rails might be cleaning up everything. I'm not sure.

**Comment by kushkella** [comment]
I think I've figured out the issue. It seems like that Grape::Formatter::Rabl uses class level instance variables which are definitely not thread-safe. 

When I first tried this out, I had cache sources turned on in both grape-rabl and rabl. And for some reason, it only gave error when restarting the server. But with cache turned off, it gave error for every request. I think the class level instance variables were cleared out during the time between rendering a request and fetching the template. With cache turned on fetching template was done in no-time, which might have stopped this error. And when you restart the templates are available in cache so there is chance that the delay in fetching the template would have caused the same behavior.

But today I disabled all caching and ran an experiment with concurrent requests. And most of the requests failed without even restarting puma. I then changed the formatter to use Thread local variables like this.

```
module Grape
  module Formatter
    module Rabl
      class << self

        def call(object, env)
          Thread.current[:env]      = env
          Thread.current[:endpoint] = env['api.endpoint']

          if rablable?
            rabl do |template|
              engine = tilt_template(template)
              output = engine.render endpoint, locals
              if layout_template
                layout_template.render(endpoint) { output }
              else
                output
              end
            end
          else
            Grape::Formatter::Json.call object, env
          end
        end

        def env
          Thread.current[:env]
        end

        def endpoint
          Thread.current[:endpoint]
        end

        private

        def view_path(template)
          if template.split('.')[-1] == 'rabl'
            File.join(env['api.tilt.root'], template)
          else
            File.join(env['api.tilt.root'], (template + '.rabl'))
          end
        end

        def rablable?
          !!rabl_template
        end

        def rabl
          fail 'missing rabl template' unless rabl_template
          set_view_root unless env['api.tilt.root']
          yield rabl_template
        end

        def locals
          env['api.tilt.rabl_locals'] || endpoint.options[:route_options][:rabl_locals] || {}
        end

        def rabl_template
          env['api.tilt.rabl'] || endpoint.options[:route_options][:rabl]
        end

        def set_view_root
          fail "Use Rack::Config to set 'api.tilt.root' in config.ru"
        end

        def tilt_template(template)
          if Grape::Rabl.configuration.cache_template_loading
            tilt_cache.fetch(template) { ::Tilt.new(view_path(template), tilt_options) }
          else
            ::Tilt.new(view_path(template), tilt_options)
          end
        end

        def tilt_cache
          @tilt_cache ||= ::Tilt::Cache.new
        end

        def tilt_options
          { format: env['api.format'], view_path: env['api.tilt.root'] }
        end

        def layout_template
          layout_path = view_path(env['api.tilt.layout'] || 'layouts/application')
          if Grape::Rabl.configuration.cache_template_loading
            tilt_cache.fetch(layout_path) { ::Tilt.new(layout_path, tilt_options) if File.exist?(layout_path) }
          else
            ::Tilt.new(layout_path, tilt_options) if File.exist?(layout_path)
          end
        end
      end
    end
  end
end
```

And the errors stopped coming. I didn't change @tilt_cache but I think that should be changed as well. My theory may be far-fetched as my previous theories :) but I would like you to go through it and let me know if it makes sense. If it does, what solution would you propose.

**Comment by dblock** [comment]
This makes sense. Can you just try to PR the changes you made?

**Comment by kushkella** [comment]
Yeah, the sample code is more of a hack because using thread local variables can cause name conflicts with other gems/code etc. I'll follow a different pattern and submit a PR. Thanks!

**Comment by dblock** [comment]
Closed via https://github.com/LTe/grape-rabl/pull/38.
