### ISSUE TITLE
 uninitialized constant Grape::Formatter::Rabl

### ISSUE THREAD

**Issue by martinezcoder** [LTe/grape-rabl#39]
I have upgrade to 0.4.0, but

This line of code in my API controller:
```ruby
formatter :json, Grape::Formatter::Rabl
```
Is returning now this error:
````

uninitialized constant Grape::Formatter::Rabl (NameError)
````

**Comment by nysthee** [comment]
When is this fix released? I see that the ruby gems version is behind the version of master.

**Comment by dblock** [comment]
I just cut a release @nysthee, sorry for the wait.

**Comment by nysthee** [comment]
Thanks! :ok_hand:

**Comment by martinezcoder** [comment]
:ok_hand: thanks!
